export const AUTHENTICATION = "AUTHENTICATION";
export const AUTHENTICATION_SUCCESS = "AUTHENTICATION_SUCCESS";
export const AUTHENTICATION_ERROR = "AUTHENTICATION_ERROR";

export const GET_USERS = "GET_USERS";
export const GET_USERS_SUCCESS = "GET_USERS_SUCCESS";
export const GET_USERS_ERROR = "GET_USERS_ERROR";

export const GET_USER_WALLET = "GET_USER_WALLET";
export const GET_USER_WALLET_SUCCESS = "GET_USER_WALLET_SUCCESS";
export const GET_USER_WALLET_ERROR = "GET_USER_WALLET_ERROR";

export const EDIT_USER_WALLET = "EDIT_USER_WALLET";
export const EDIT_USER_WALLET_SUCCESS = "EDIT_USER_WALLET_SUCCESS";
export const EDIT_USER_WALLET_ERROR = "EDIT_USER_WALLET_ERROR";
